### ISSUE TITLE
can i close the client ? 

### ISSUE THREAD

**Issue by yangmingyu1984** [baking-bad/pysignalr#26]
in my case,  i want to disconnect from server sometimes,  is there any way to do this?

**Comment by droserasprout** [comment]
Instead of calling `client.run` directly, create a task, then cancel it when needed:

```python
task = asyncio.create_task(client.run())

...

task.cancel()
```

**Comment by AntoninoBonanno** [comment]
I've tried several things but I get an async error when I press CTRL+C.

pysignalr\client.py:151
```
2025-09-10 16:33:34,528 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<SignalRClient.run() running at \pysignalr\client.py:151> wait_for=<_GatheringFuture pending cb=[Task.__wakeup()]> cb=[Task.__wakeup()]>
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x04632EC8>
Traceback (most recent call last):
  File "\lib\asyncio\proactor_events.py", line 116, in __del__
  File "\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Program Files\JetBrains\PyCharm 2024.2.3\plugins\python\helpers-pro\pydevd_asyncio\pydevd_nest_asyncio.py", line 307, in call_soon
  File "\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
2025-09-10 16:33:34,530 - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<Connection.keepalive() running at C\websockets\asyncio\connection.py:815> wait_for=<Future pending cb=[Task.__wakeup()]>>
Exception ignored in: <coroutine object WebsocketTransport._process at 0x051771B0>
Traceback (most recent call last):
  File "\pysignalr\transport\websocket.py", line 286, in _process
  File "\websockets\asyncio\connection.py", line 303, in recv
  File "\websockets\asyncio\messages.py", line 159, in get
  File "\websockets\asyncio\messages.py", line 53, in get
  File "\asyncio\futures.py", line 156, in cancel
  File "\asyncio\futures.py", line 171, in __schedule_callbacks
  File "C:\Program Files\JetBrains\PyCharm 2024.2.3\plugins\python\helpers-pro\pydevd_asyncio\pydevd_nest_asyncio.py", line 307, in call_soon
  File "\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <async_generator object __aiter__ at 0x0725E610>
Traceback (most recent call last):
  File "\pysignalr\transport\websocket.py", line 217, in _loop
RuntimeError: async generator ignored GeneratorExit
```

**Need a clean way to close websocket connection**
